apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: store-api
  template: 
    metadata: 
      labels: 
        name: store-api  
    spec:
      containers:
        - name: store-api-con
          image: anjali0418/store-api:02
          ports: 
            - containerPort: 5000
          #env:
           # - name: MONGODB_URI
            #  value: "mongodb://mongodb-service/store-platform"
          envFrom:
            - configMapRef:
                name: store-api-config